"""add heart rate and cadence columns to runs

Revision ID: 649f5dedfd17
Revises: 3c7eb173531a
Create Date: 2026-06-19 17:17:52.156077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649f5dedfd17'
down_revision: Union[str, Sequence[str], None] = '3c7eb173531a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('avg_heart_rate_bpm', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('max_heart_rate_bpm', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('avg_cadence_spm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'avg_cadence_spm')
    op.drop_column('runs', 'max_heart_rate_bpm')
    op.drop_column('runs', 'avg_heart_rate_bpm')
    # ### end Alembic commands ###
