"""add course and accuracy fields to run_points

Revision ID: 73cdf3bdbdbb
Revises: 2d68ffdccfd1
Create Date: 2026-06-19 17:43:26.633234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cdf3bdbdbb'
down_revision: Union[str, Sequence[str], None] = '2d68ffdccfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
